eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
      - id: bookstore_backend
        uri: lb://bookstore-backend
        predicates:
        - Path=/books/**, /orders/**, /users/**, /carts/**, /login/**, /orders/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH

server:
  port: 8081